[package]
name = "practice-partner"
version = "0.1.0"
edition = "2021"


[dependencies]
serenity = { version = "0.11.5", features = ["client", "gateway", "rustls_backend", "model"] }
tokio = { version = "1.20.1", features = ["macros", "rt-multi-thread"] }
dotenv = "0.15.0"
